In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("customer_trends.csv")

In [5]:
df.head()

,Customer_ID,Age,Gender,Item_Purchased,Category,Purchase_Amount,Location,Size,Color,Season,Review_Rating,Subscription_Status,Shipping_Type,Discount_Applied,Promo_Code_Used,Previous_Purchases,Payment_Method,Frequency_of_Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.0,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.0,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.0,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,4.0,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,3.0,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [6]:
df.tail()

,Customer_ID,Age,Gender,Item_Purchased,Category,Purchase_Amount,Location,Size,Color,Season,Review_Rating,Subscription_Status,Shipping_Type,Discount_Applied,Promo_Code_Used,Previous_Purchases,Payment_Method,Frequency_of_Purchases
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [7]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Item_Purchased', 'Category',
       'Purchase_Amount', 'Location', 'Size', 'Color', 'Season',
       'Review_Rating', 'Subscription_Status', 'Shipping_Type',
       'Discount_Applied', 'Promo_Code_Used', 'Previous_Purchases',
       'Payment_Method', 'Frequency_of_Purchases'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer_ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item_Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase_Amount         3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review_Rating           3863 non-null   float64
 11  Subscription_Status     3900 non-null   object
 12  Shipping_Type           3900 non-null   object
 13  Discount_Applied        3900 non-null   object
 14  Promo_Code_Used         3900 non-null   object
 15  Previous_Purchases      3900 non-null   int64
 16  Payment_Method          3900 non-null   object
 17  Frequency_of_Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [9]:
df.isnull().sum()

Customer_ID                0
Age                        0
Gender                     0
Item_Purchased             0
Category                   0
Purchase_Amount            0
Location                   0
Size                       0
Color                      0
Season                     0
Review_Rating             37
Subscription_Status        0
Shipping_Type              0
Discount_Applied           0
Promo_Code_Used            0
Previous_Purchases         0
Payment_Method             0
Frequency_of_Purchases     0
dtype: int64

In [11]:
df["Review_Rating"] = df["Review_Rating"].fillna(
    df["Review_Rating"].mean()
)

In [13]:
df["Review_Rating"].isnull().sum()

np.int64(0)

In [14]:
df.duplicated().sum()

np.int64(0)

In [20]:
mean_purchase = np.mean(df["Purchase_Amount"])
max_purchase = np.max(df["Purchase_Amount"])
min_purchase = np.min(df["Purchase_Amount"])

print("Mean Purchase Amount:", mean_purchase)
print("Maximum Purchase Amount:", max_purchase)
print("Minimum Purchase Amount:", min_purchase)

Mean Purchase Amount: 59.76435897435898
Maximum Purchase Amount: 100
Minimum Purchase Amount: 20

In [22]:
df["Category"].value_counts()

Category
Clothing       1737
Accessories    1240
Footwear        599
Outerwear       324
Name: count, dtype: int64

In [26]:
df.groupby("Season")["Purchase_Amount"].sum()

Season
Fall      60018
Spring    58679
Summer    55777
Winter    58607
Name: Purchase_Amount, dtype: int64